# 全スキルインストールの場合は空リストにする
google-gemini/gemini-skills:
firebase/agent-skills:

# 個別インストールの場合はリストを書く
vercel-labs/skills:
  - find-skills
rodydavis/skills:
  - flutter-control-and-screenshot
anthropics/skills:
  - frontend-design
nextlevelbuilder/ui-ux-pro-max-skill:
  - ui-ux-pro-max
better-auth/skills:
  - better-auth-security-best-practices
obra/superpowers:
  - brainstorming
  - test-driven-development
  - using-superpowers
  - verification-before-completion
juparave/dotfiles:
  - flutter-riverpod-expert
wshobson/agents:
  - api-design-principles
  - nodejs-backend-patterns
  - design-system-patterns
  - mobile-android-design
  - mobile-ios-design
  - responsive-design
madteacher/mad-agents-skills:
  - dart-drift
  - flutter-adaptive-ui
  - flutter-animations
  # - flutter-architecture
  - flutter-drift
  - flutter-internationalization
  - flutter-navigation
  - flutter-networking
  - flutter-testing
